interface KoreanLocation {
	sido: { sido: string; codeNm: string }[]
	sigugun: { sido: string; sigugun: string; codeNm: string }[]
}

const hangjun: KoreanLocation = {
	sido: [
		{ sido: '서울특별시', codeNm: '서울특별시' },
		{ sido: '부산광역시', codeNm: '부산광역시' },
		{ sido: '대구광역시', codeNm: '대구광역시' },
		{ sido: '인천광역시', codeNm: '인천광역시' },
		{ sido: '광주광역시', codeNm: '광주광역시' },
		{ sido: '대전광역시', codeNm: '대전광역시' },
		{ sido: '울산광역시', codeNm: '울산광역시' },
		{ sido: '세종특별자치시', codeNm: '세종특별자치시' },
		{ sido: '경기도', codeNm: '경기도' },
		{ sido: '강원도', codeNm: '강원도' },
		{ sido: '충청북도', codeNm: '충청북도' },
		{ sido: '충청남도', codeNm: '충청남도' },
		{ sido: '전라북도', codeNm: '전라북도' },
		{ sido: '전라남도', codeNm: '전라남도' },
		{ sido: '경상북도', codeNm: '경상북도' },
		{ sido: '경상남도', codeNm: '경상남도' },
		{ sido: '제주특별자치도', codeNm: '제주특별자치도' },
	],
	sigugun: [
		/* 서울 */
		{ sido: '서울특별시', sigugun: '종로구', codeNm: '종로구' },
		{ sido: '서울특별시', sigugun: '중구', codeNm: '중구' },
		{ sido: '서울특별시', sigugun: '용산구', codeNm: '용산구' },
		{ sido: '서울특별시', sigugun: '성동구', codeNm: '성동구' },
		{ sido: '서울특별시', sigugun: '광진구', codeNm: '광진구' },
		{ sido: '서울특별시', sigugun: '동대문구', codeNm: '동대문구' },
		{ sido: '서울특별시', sigugun: '중랑구', codeNm: '중랑구' },
		{ sido: '서울특별시', sigugun: '성북구', codeNm: '성북구' },
		{ sido: '서울특별시', sigugun: '강북구', codeNm: '강북구' },
		{ sido: '서울특별시', sigugun: '도봉구', codeNm: '도봉구' },
		{ sido: '서울특별시', sigugun: '노원구', codeNm: '노원구' },
		{ sido: '서울특별시', sigugun: '은평구', codeNm: '은평구' },
		{ sido: '서울특별시', sigugun: '서대문구', codeNm: '서대문구' },
		{ sido: '서울특별시', sigugun: '마포구', codeNm: '마포구' },
		{ sido: '서울특별시', sigugun: '양천구', codeNm: '양천구' },
		{ sido: '서울특별시', sigugun: '강서구', codeNm: '강서구' },
		{ sido: '서울특별시', sigugun: '구로구', codeNm: '구로구' },
		{ sido: '서울특별시', sigugun: '금천구', codeNm: '금천구' },
		{ sido: '서울특별시', sigugun: '영등포구', codeNm: '영등포구' },
		{ sido: '서울특별시', sigugun: '동작구', codeNm: '동작구' },
		{ sido: '서울특별시', sigugun: '관악구', codeNm: '관악구' },
		{ sido: '서울특별시', sigugun: '서초구', codeNm: '서초구' },
		{ sido: '서울특별시', sigugun: '강남구', codeNm: '강남구' },
		{ sido: '서울특별시', sigugun: '송파구', codeNm: '송파구' },
		{ sido: '서울특별시', sigugun: '강동구', codeNm: '강동구' },

		/* 부산 */
		{ sido: '부산광역시', sigugun: '중구', codeNm: '중구' },
		{ sido: '부산광역시', sigugun: '서구', codeNm: '서구' },
		{ sido: '부산광역시', sigugun: '동구', codeNm: '동구' },
		{ sido: '부산광역시', sigugun: '영도구', codeNm: '영도구' },
		{ sido: '부산광역시', sigugun: '부산진구', codeNm: '부산진구' },
		{ sido: '부산광역시', sigugun: '동래구', codeNm: '동래구' },
		{ sido: '부산광역시', sigugun: '남구', codeNm: '남구' },
		{ sido: '부산광역시', sigugun: '북구', codeNm: '북구' },
		{ sido: '부산광역시', sigugun: '해운대구', codeNm: '해운대구' },
		{ sido: '부산광역시', sigugun: '사하구', codeNm: '사하구' },
		{ sido: '부산광역시', sigugun: '금정구', codeNm: '금정구' },
		{ sido: '부산광역시', sigugun: '강서구', codeNm: '강서구' },
		{ sido: '부산광역시', sigugun: '연제구', codeNm: '연제구' },
		{ sido: '부산광역시', sigugun: '수영구', codeNm: '수영구' },
		{ sido: '부산광역시', sigugun: '사상구', codeNm: '사상구' },
		{ sido: '부산광역시', sigugun: '기장군', codeNm: '기장군' },

		/* 대구 */
		{ sido: '대구광역시', sigugun: '중구', codeNm: '중구' },
		{ sido: '대구광역시', sigugun: '동구', codeNm: '동구' },
		{ sido: '대구광역시', sigugun: '서구', codeNm: '서구' },
		{ sido: '대구광역시', sigugun: '남구', codeNm: '남구' },
		{ sido: '대구광역시', sigugun: '북구', codeNm: '북구' },
		{ sido: '대구광역시', sigugun: '수성구', codeNm: '수성구' },
		{ sido: '대구광역시', sigugun: '달서구', codeNm: '달서구' },
		{ sido: '대구광역시', sigugun: '달성군', codeNm: '달성군' },

		/* 인천 */
		{ sido: '인천광역시', sigugun: '중구', codeNm: '중구' },
		{ sido: '인천광역시', sigugun: '동구', codeNm: '동구' },
		{ sido: '인천광역시', sigugun: '연수구', codeNm: '연수구' },
		{ sido: '인천광역시', sigugun: '남동구', codeNm: '남동구' },
		{ sido: '인천광역시', sigugun: '부평구', codeNm: '부평구' },
		{ sido: '인천광역시', sigugun: '계양구', codeNm: '계양구' },
		{ sido: '인천광역시', sigugun: '서구', codeNm: '서구' },
		{ sido: '인천광역시', sigugun: '미추홀구', codeNm: '미추홀구' },
		{ sido: '인천광역시', sigugun: '강화군', codeNm: '강화군' },
		{ sido: '인천광역시', sigugun: '옹진군', codeNm: '옹진군' },

		/* 광주 */
		{ sido: '광주광역시', sigugun: '동구', codeNm: '동구' },
		{ sido: '광주광역시', sigugun: '서구', codeNm: '서구' },
		{ sido: '광주광역시', sigugun: '남구', codeNm: '남구' },
		{ sido: '광주광역시', sigugun: '북구', codeNm: '북구' },
		{ sido: '광주광역시', sigugun: '광산구', codeNm: '광산구' },

		/* 대전 */
		{ sido: '대전광역시', sigugun: '동구', codeNm: '동구' },
		{ sido: '대전광역시', sigugun: '중구', codeNm: '중구' },
		{ sido: '대전광역시', sigugun: '서구', codeNm: '서구' },
		{ sido: '대전광역시', sigugun: '유성구', codeNm: '유성구' },
		{ sido: '대전광역시', sigugun: '대덕구', codeNm: '대덕구' },

		/* 울산 */
		{ sido: '울산광역시', sigugun: '중구', codeNm: '중구' },
		{ sido: '울산광역시', sigugun: '남구', codeNm: '남구' },
		{ sido: '울산광역시', sigugun: '동구', codeNm: '동구' },
		{ sido: '울산광역시', sigugun: '북구', codeNm: '북구' },
		{ sido: '울산광역시', sigugun: '울주군', codeNm: '울주군' },

		/* 세종특별자치 */
		{
			sido: '세종특별자치시',
			sigugun: '세종특별자치시',
			codeNm: '세종특별자치시',
		},

		/* 경기도 */
		{ sido: '경기도', sigugun: '수원시', codeNm: '수원시' },
		{ sido: '경기도', sigugun: '성남시', codeNm: '성남시' },
		{ sido: '경기도', sigugun: '의정부시', codeNm: '의정부시' },
		{ sido: '경기도', sigugun: '안양시', codeNm: '안양시' },
		{ sido: '경기도', sigugun: '부천시', codeNm: '부천시' },
		{ sido: '경기도', sigugun: '광명시', codeNm: '광명시' },
		{ sido: '경기도', sigugun: '평택시', codeNm: '평택시' },
		{ sido: '경기도', sigugun: '동두천시', codeNm: '동두천시' },
		{ sido: '경기도', sigugun: '안산시', codeNm: '안산시' },
		{ sido: '경기도', sigugun: '고양시', codeNm: '고양시' },
		{ sido: '경기도', sigugun: '과천시', codeNm: '과천시' },
		{ sido: '경기도', sigugun: '구리시', codeNm: '구리시' },
		{ sido: '경기도', sigugun: '남양주시', codeNm: '남양주시' },
		{ sido: '경기도', sigugun: '오산시', codeNm: '오산시' },
		{ sido: '경기도', sigugun: '시흥시', codeNm: '시흥시' },
		{ sido: '경기도', sigugun: '군포시', codeNm: '군포시' },
		{ sido: '경기도', sigugun: '의왕시', codeNm: '의왕시' },
		{ sido: '경기도', sigugun: '하남시', codeNm: '하남시' },
		{ sido: '경기도', sigugun: '용인시', codeNm: '용인시' },
		{ sido: '경기도', sigugun: '파주시', codeNm: '파주시' },
		{ sido: '경기도', sigugun: '이천시', codeNm: '이천시' },
		{ sido: '경기도', sigugun: '안성시', codeNm: '안성시' },
		{ sido: '경기도', sigugun: '김포시', codeNm: '김포시' },
		{ sido: '경기도', sigugun: '화성시', codeNm: '화성시' },
		{ sido: '경기도', sigugun: '광주시', codeNm: '광주시' },
		{ sido: '경기도', sigugun: '양주시', codeNm: '양주시' },
		{ sido: '경기도', sigugun: '포천시', codeNm: '포천시' },
		{ sido: '경기도', sigugun: '여주시', codeNm: '여주시' },
		{ sido: '경기도', sigugun: '연천군', codeNm: '연천군' },
		{ sido: '경기도', sigugun: '가평군', codeNm: '가평군' },
		{ sido: '경기도', sigugun: '양평군', codeNm: '양평군' },

		/* 강원도 */
		{ sido: '강원도', sigugun: '춘천시', codeNm: '춘천시' },
		{ sido: '강원도', sigugun: '원주시', codeNm: '원주시' },
		{ sido: '강원도', sigugun: '강릉시', codeNm: '강릉시' },
		{ sido: '강원도', sigugun: '동해시', codeNm: '동해시' },
		{ sido: '강원도', sigugun: '태백시', codeNm: '태백시' },
		{ sido: '강원도', sigugun: '속초시', codeNm: '속초시' },
		{ sido: '강원도', sigugun: '삼척시', codeNm: '삼척시' },
		{ sido: '강원도', sigugun: '홍천군', codeNm: '홍천군' },
		{ sido: '강원도', sigugun: '횡성군', codeNm: '횡성군' },
		{ sido: '강원도', sigugun: '영월군', codeNm: '영월군' },
		{ sido: '강원도', sigugun: '평창군', codeNm: '평창군' },
		{ sido: '강원도', sigugun: '정선군', codeNm: '정선군' },
		{ sido: '강원도', sigugun: '철원군', codeNm: '철원군' },
		{ sido: '강원도', sigugun: '화천군', codeNm: '화천군' },
		{ sido: '강원도', sigugun: '양구군', codeNm: '양구군' },
		{ sido: '강원도', sigugun: '인제군', codeNm: '인제군' },
		{ sido: '강원도', sigugun: '고성군', codeNm: '고성군' },
		{ sido: '강원도', sigugun: '양양군', codeNm: '양양군' },

		/* 충북 */
		{ sido: '충청북도', sigugun: '청주시', codeNm: '청주시' },
		{ sido: '충청북도', sigugun: '충주시', codeNm: '충주시' },
		{ sido: '충청북도', sigugun: '제천시', codeNm: '제천시' },
		{ sido: '충청북도', sigugun: '보은군', codeNm: '보은군' },
		{ sido: '충청북도', sigugun: '옥천군', codeNm: '옥천군' },
		{ sido: '충청북도', sigugun: '영동군', codeNm: '영동군' },
		{ sido: '충청북도', sigugun: '증평군', codeNm: '증평군' },
		{ sido: '충청북도', sigugun: '진천군', codeNm: '진천군' },
		{ sido: '충청북도', sigugun: '괴산군', codeNm: '괴산군' },
		{ sido: '충청북도', sigugun: '음성군', codeNm: '음성군' },
		{ sido: '충청북도', sigugun: '단양군', codeNm: '단양군' },

		/* 충남 */
		{ sido: '충청남도', sigugun: '천안시', codeNm: '천안시' },
		{ sido: '충청남도', sigugun: '공주시', codeNm: '공주시' },
		{ sido: '충청남도', sigugun: '보령시', codeNm: '보령시' },
		{ sido: '충청남도', sigugun: '아산시', codeNm: '아산시' },
		{ sido: '충청남도', sigugun: '서산시', codeNm: '서산시' },
		{ sido: '충청남도', sigugun: '논산시', codeNm: '논산시' },
		{ sido: '충청남도', sigugun: '계룡시', codeNm: '계룡시' },
		{ sido: '충청남도', sigugun: '당진시', codeNm: '당진시' },
		{ sido: '충청남도', sigugun: '금산군', codeNm: '금산군' },
		{ sido: '충청남도', sigugun: '부여군', codeNm: '부여군' },
		{ sido: '충청남도', sigugun: '서천군', codeNm: '서천군' },
		{ sido: '충청남도', sigugun: '청양군', codeNm: '청양군' },
		{ sido: '충청남도', sigugun: '홍성군', codeNm: '홍성군' },
		{ sido: '충청남도', sigugun: '예산군', codeNm: '예산군' },
		{ sido: '충청남도', sigugun: '태안군', codeNm: '태안군' },

		/* 전북 */
		{ sido: '전라북도', sigugun: '전주시', codeNm: '전주시' },
		{ sido: '전라북도', sigugun: '군산시', codeNm: '군산시' },
		{ sido: '전라북도', sigugun: '익산시', codeNm: '익산시' },
		{ sido: '전라북도', sigugun: '정읍시', codeNm: '정읍시' },
		{ sido: '전라북도', sigugun: '남원시', codeNm: '남원시' },
		{ sido: '전라북도', sigugun: '김제시', codeNm: '김제시' },
		{ sido: '전라북도', sigugun: '완주군', codeNm: '완주군' },
		{ sido: '전라북도', sigugun: '진안군', codeNm: '진안군' },
		{ sido: '전라북도', sigugun: '무주군', codeNm: '무주군' },
		{ sido: '전라북도', sigugun: '장수군', codeNm: '장수군' },
		{ sido: '전라북도', sigugun: '임실군', codeNm: '임실군' },
		{ sido: '전라북도', sigugun: '순창군', codeNm: '순창군' },
		{ sido: '전라북도', sigugun: '고창군', codeNm: '고창군' },
		{ sido: '전라북도', sigugun: '부안군', codeNm: '부안군' },

		/* 전남 */
		{ sido: '전라남도', sigugun: '목포시', codeNm: '목포시' },
		{ sido: '전라남도', sigugun: '여수시', codeNm: '여수시' },
		{ sido: '전라남도', sigugun: '순천시', codeNm: '순천시' },
		{ sido: '전라남도', sigugun: '나주시', codeNm: '나주시' },
		{ sido: '전라남도', sigugun: '광양시', codeNm: '광양시' },
		{ sido: '전라남도', sigugun: '담양군', codeNm: '담양군' },
		{ sido: '전라남도', sigugun: '곡성군', codeNm: '곡성군' },
		{ sido: '전라남도', sigugun: '구례군', codeNm: '구례군' },
		{ sido: '전라남도', sigugun: '고흥군', codeNm: '고흥군' },
		{ sido: '전라남도', sigugun: '보성군', codeNm: '보성군' },
		{ sido: '전라남도', sigugun: '화순군', codeNm: '화순군' },
		{ sido: '전라남도', sigugun: '장흥군', codeNm: '장흥군' },
		{ sido: '전라남도', sigugun: '강진군', codeNm: '강진군' },
		{ sido: '전라남도', sigugun: '해남군', codeNm: '해남군' },
		{ sido: '전라남도', sigugun: '영암군', codeNm: '영암군' },
		{ sido: '전라남도', sigugun: '무안군', codeNm: '무안군' },
		{ sido: '전라남도', sigugun: '함평군', codeNm: '함평군' },
		{ sido: '전라남도', sigugun: '영광군', codeNm: '영광군' },
		{ sido: '전라남도', sigugun: '장성군', codeNm: '장성군' },
		{ sido: '전라남도', sigugun: '완도군', codeNm: '완도군' },
		{ sido: '전라남도', sigugun: '진도군', codeNm: '진도군' },
		{ sido: '전라남도', sigugun: '신안군', codeNm: '신안군' },

		/* 경북 */
		{ sido: '경상북도', sigugun: '포항시', codeNm: '포항시' },
		{ sido: '경상북도', sigugun: '경주시', codeNm: '경주시' },
		{ sido: '경상북도', sigugun: '김천시', codeNm: '김천시' },
		{ sido: '경상북도', sigugun: '안동시', codeNm: '안동시' },
		{ sido: '경상북도', sigugun: '구미시', codeNm: '구미시' },
		{ sido: '경상북도', sigugun: '영주시', codeNm: '영주시' },
		{ sido: '경상북도', sigugun: '영천시', codeNm: '영천시' },
		{ sido: '경상북도', sigugun: '상주시', codeNm: '상주시' },
		{ sido: '경상북도', sigugun: '문경시', codeNm: '문경시' },
		{ sido: '경상북도', sigugun: '경산시', codeNm: '경산시' },
		{ sido: '경상북도', sigugun: '군위군', codeNm: '군위군' },
		{ sido: '경상북도', sigugun: '의성군', codeNm: '의성군' },
		{ sido: '경상북도', sigugun: '청송군', codeNm: '청송군' },
		{ sido: '경상북도', sigugun: '영양군', codeNm: '영양군' },
		{ sido: '경상북도', sigugun: '영덕군', codeNm: '영덕군' },
		{ sido: '경상북도', sigugun: '청도군', codeNm: '청도군' },
		{ sido: '경상북도', sigugun: '고령군', codeNm: '고령군' },
		{ sido: '경상북도', sigugun: '성주군', codeNm: '성주군' },
		{ sido: '경상북도', sigugun: '칠곡군', codeNm: '칠곡군' },
		{ sido: '경상북도', sigugun: '예천군', codeNm: '예천군' },
		{ sido: '경상북도', sigugun: '봉화군', codeNm: '봉화군' },
		{ sido: '경상북도', sigugun: '울진군', codeNm: '울진군' },
		{ sido: '경상북도', sigugun: '울릉군', codeNm: '울릉군' },

		/* 경남 */
		{ sido: '경상남도', sigugun: '창원시', codeNm: '창원시' },
		{ sido: '경상남도', sigugun: '진주시', codeNm: '진주시' },
		{ sido: '경상남도', sigugun: '통영시', codeNm: '통영시' },
		{ sido: '경상남도', sigugun: '사천시', codeNm: '사천시' },
		{ sido: '경상남도', sigugun: '김해시', codeNm: '김해시' },
		{ sido: '경상남도', sigugun: '밀양시', codeNm: '밀양시' },
		{ sido: '경상남도', sigugun: '거제시', codeNm: '거제시' },
		{ sido: '경상남도', sigugun: '양산시', codeNm: '양산시' },
		{ sido: '경상남도', sigugun: '의령군', codeNm: '의령군' },
		{ sido: '경상남도', sigugun: '함안군', codeNm: '함안군' },
		{ sido: '경상남도', sigugun: '창녕군', codeNm: '창녕군' },
		{ sido: '경상남도', sigugun: '고성군', codeNm: '고성군' },
		{ sido: '경상남도', sigugun: '남해군', codeNm: '남해군' },
		{ sido: '경상남도', sigugun: '하동군', codeNm: '하동군' },
		{ sido: '경상남도', sigugun: '산청군', codeNm: '산청군' },
		{ sido: '경상남도', sigugun: '함양군', codeNm: '함양군' },
		{ sido: '경상남도', sigugun: '거창군', codeNm: '거창군' },
		{ sido: '경상남도', sigugun: '합천군', codeNm: '합천군' },

		/* 제주 */
		{ sido: '제주특별자치도', sigugun: '제주시', codeNm: '제주시' },
		{ sido: '제주특별자치도', sigugun: '서귀포시', codeNm: '서귀포시' },
	],
}
export default hangjun
